#!/bin/bash

set -e

FENICS_PYTHON="${FENICS_PYTHON:-python}"
FENICS_BUILD_TYPE="${FENICS_BUILD_TYPE:-Release}"

if [ -z "${FENICS_SRC_DIR}" ]; then
    echo "FENICS_SRC_DIR must be defined" >&2
    exit -1
fi

if [ -z "${FENICS_PREFIX}" ]; then
    echo "FENICS_PREFIX must be defined" >&2
    exit -1
fi

function build_cmake () {
    # build a project with cmake (dolfin, mshr)
    project="$1"
    echo "FENICS-BUILDER: Building $project with CMake..."

    build="$FENICS_SRC_DIR/$project/build"
    mkdir -p "$build"
    cd "$build"
    cmake ../ -DCMAKE_INSTALL_PREFIX=${FENICS_PREFIX} -DCMAKE_BUILD_TYPE=${FENICS_BUILD_TYPE} \
              -Wno-dev -DPYTHON_EXECUTABLE:FILEPATH=$(which ${FENICS_PYTHON}) ${CMAKE_EXTRA_ARGS}
    make
    make install
}

function build () {
    for project in $@; do
        echo "FENICS-BUILDER: Building $project..."
        path="$FENICS_SRC_DIR/$project"
        if [ ! -d "$path" ]; then
            echo "FENICS-BUILDER: $project source cannot be found at $path. Please run fenics-pull first."
            exit -1
        fi
        if [ -e $path/CMakeLists.txt ]; then
            build_cmake "$project"
        else
            cd "$path"
            ${FENICS_PYTHON} -m pip install --prefix=${FENICS_PREFIX} --no-deps --upgrade .
        fi
    done
}

if [ -z "$1" ]; then
    if [ "${FENICS_VERSION}" == "1.6.0" ]; then
        build fiat instant ufl ffc dolfin
    else
        build fiat dijitso instant ufl ffc dolfin mshr
    fi
else
    build $@
fi
