FROM DOCKER_NAMESPACE/python:3.5
MAINTAINER René Milk <rene.milk@wwu.de>

RUN /root/install_requirements.bash
RUN $FENICS_HOME/build_and_test.bash

ENV LD_LIBRARY_PATH=/usr/local/lib/python3.5/site-packages/PySide/:${LD_LIBRARY_PATH}

VOLUME /src
WORKDIR /src
ENV PYTHONPATH /src/src
